### ISSUE TITLE
[Bug] Webinterface not working with Linux Appimage

### ISSUE THREAD

**Issue by yoshnopa** [jcfain/XTPlayer#2]
Thank you for developing this extensive program!

I found that the Appimage for linux (I tested x86_64) does not work headless with the webinterface out of the box. 
From debugging and extracting the Appimage I found the culprit being that the static webfiles were not present in the Appimage at all, meaning that the program fails to deliver the html, js and css files respectively.
A workaround I found was to extract the Appimage and add the missing folders in the usr/bin folder. I took www, themes, images and also lib (the latter may be overkill, just wanted to make sure), from the source code zip (in the subfoldedr src), and now it works.

This is however of course not how its supposed to be, so I'd advice to adjust the Appimage creation script to include those essential folders. I also didn't test the GUI version, so there may be similar issues there.

**Comment by jcfain** [comment]
I believe this was a deploy issue and I'm pretty sure it has been resolved.
